### ISSUE TITLE
Live API Context field is not filled in

### ISSUE THREAD

**Issue by ManonSchipper** [patrickkivits/bunq-for-woocommerce#1]
Hallo,

Dank voor de plugin. Ik heb deze geïnstalleerd op mijn website, maar zie dat het niet werkt. 
Bij het invullen van de API sleutel die ik in de Bunq App heb gegenereerd, zie ik dat;

- Er geen bankrekeningnummer gekozen kan worden. De melding "API Key not valid or not set up yet" is de enige optie in de dropdown

- Het veld met de Live API Context blijft leeg en wordt niet ingevuld na het invullen van de API Sleutel

Hoe kan ik deze issues verhelpen?

MVG

**Comment by ManonSchipper** [comment]
Het veld met de Live API Context is inmiddels opgelost, maar ik kan mijn Bunq rekeningnummer niet selecteren. De melding "API Key not valid or not set up yet" is nog steeds de enige optie in de dropdown.

Is er wellicht een oplossing voor dit probleem?

Met vriendelijke groet,

Manon

**Comment by patrickkivits** [comment]
Hoi Manon,

Heb je het IP adres van de server waar je de plugin gebruikt gewhitelist voor de gebruikte API key?

Als je de API key voor de eerste keer gebruikt wordt dat IP adres automatisch toegestaan, echter vanaf elk ander IP adres is toegang dan niet meer toegestaan tenzij deze expliciet hieraan wordt toegevoegd of gebruik maakt van een 'wildcard' welke toegang verleend aan alle IP adressen (niet aan te raden i.v.m. beveiliging).

Als je de gebruikte API key dus al eerder op een andere server op apparaat gebruikt hebt kan het dus zijn dat hij nu daarom niet werkt voordat het nieuwe (locatie van de plugin) IP adres ook wordt toegelaten.

Met vriendelijke groet,

Patrick

**Comment by ManonSchipper** [comment]
De API code is inmiddels wel geaccepteerd. Maar ik kan geen bankrekeningnummer selecteren. (zie bijlage voor screenshot).

![Schermafbeelding 2020-09-10 om 15 14 47](https://user-images.githubusercontent.com/71076267/92733938-64bdb200-f378-11ea-9138-ccb209427719.png)

**Comment by ManonSchipper** [comment]
Blijkbaar gaat er toch iets mis. Bij mij is de button "OAuth Authorization Request" nergens zichtbaar. Ik hoop niet dat ik al te lastig ben dat ik vragen hierover stel, maar het lukt gewoon helaas niet. 

Zou de knop "OAuth Authorization Request" automatisch zichtbaar moeten zijn na invoeren van de API sleutel? Bij mij is dat helaas niet het geval.  

<img width="228" alt="image" src="https://user-images.githubusercontent.com/71076267/92742649-20ceab00-f380-11ea-9231-0e19c353bb9a.png">

**Comment by ManonSchipper** [comment]
Hoi Patrick, 

Dank! Ik ben weer een stukje dichterbij. Alleen na het invullen van de OAuth gegevens en het klikken van de OAuth Authorization Request, krijg ik het volgende scherm (zie screenshot). Met de melding "Verbinding niet gevonden". 

Waar zou dat aan kunnen liggen?


![Schermafbeelding 2020-09-11 om 11 41 41](https://user-images.githubusercontent.com/71076267/92905537-077f3a80-f424-11ea-9194-af89c8f57d06.png)

**Comment by patrickkivits** [comment]
Hoi Manon,

Ik heb zojuist de README van de plugin aangevuld met de configuratie instructies: https://github.com/patrickkivits/bunq-for-woocommerce/blob/master/readme.md#configuration

Waar het denk ik fout gaat, is dat je bent begonnen met een API Key aanmaken in de bunq app en deze heb ingevuld in de plugin settings, terwijl dit eigenlijk een OAuth app moet zijn. Het veld van de API key in de plugin settings wordt dan automatisch ingevuld na het voltooien van de stappen.

Nog een tip: Verwijder eventuele overbodige API keys die je eerder hebt aangemaakt uit de bunq app. Deze API keys geven namelijk volledige macht over je bunq account, terwijl OAuth apps dit niet doen. Gebruik van OAuth is daarom dus veiliger en de reden dat deze plugin het ook gebruikt ipv de directe API keys.

Verder is gebruik van deze plugin uiteraard op eigen risico.

Hoop dat je er met deze instructies uit komt!

**Comment by ManonSchipper** [comment]
Hallo, Patrick het is me in ieder geval veel duidelijker. Bedankt daarvoor. 

In de Bunq App wordt mij gevraagd om een Redirect URL. Om welke URL gaat dit precies?

**Comment by patrickkivits** [comment]
Hoi Manon,

Daar vul je als het goed is de volledige URL van de bunq plug-in settings pagina in.

**Comment by patrickkivits** [comment]
Hoi Manon,

Ik ga er vanuit dat het inmiddels gelukt is. Mocht je toch nog vragen hebben kun je altijd een nieuwe issue aanmaken.

Met vriendelijke groet,

Patrick

**Comment by skyedesigns-nl** [comment]
Hallo,

Dank voor de plugin. Ik heb deze geïnstalleerd op mijn website, maar zie dat het ook niet lekker werkt.
Bij het invullen van de API sleutel die ik in de Bunq App heb gegenereerd, zie ik dat;

Er geen bankrekeningnummer gekozen kan worden. De melding "API Key not valid or not set up yet" is de enige optie in de dropdown

Het veld met de Live API Context blijft leeg en wordt niet ingevuld na het invullen van de API Sleutel

Hoe kan ik deze issues verhelpen?
Want ik kom er niet uit :(

Fijne Feestdagen
