### ISSUE TITLE
Wordpress critical error after authorization

### ISSUE THREAD

**Issue by tristanriethorst19** [patrickkivits/bunq-for-woocommerce#12]
Hi Patrick,

Thank you for creating this easy to use plugin. I have used it in the past and I am now using it again. Now I am running into some trouble regarding the authorization progress. 

After setting up the plugin page url in bunq and connect it via the [OAuth Authorization Request] button it sends me straight to bunq and I go trough the setup just as you mentione in the installation note. But after redirecting me, wordpress gives me a critical error. If I go back to the plugin page I see it did connect since the live api key is filled in. But I cant select the proper account. Also in my bunq app everything looks fine with autorization etc. See screenshot for context.

Do you have any idea if it has something to do with wp/plugin versions? I am using WP6.1.1 and Woocommerce7.1.0. 
Your plugin, Woocommerce and Elementor are the only plugins installed. 

Kind regrads,
Tristan Riethorst
<img width="1439" alt="Screenshot 2022-11-16 at 13 11 52" src="https://user-images.githubusercontent.com/118358529/202179240-d5469e9c-fd4b-4186-a0b3-49161fdd291b.png">

**Comment by patrickkivits** [comment]
Hi @tristanriethorst19, you said it gives you a critical error, do you have access to the error log?

The plugin is tested on the latest version of Wordpress and WooCommerce.

**Comment by tristanriethorst19** [comment]
Hi @patrickkivits ,
Nederlands gaat wat makkelijker. Excuses voor de late reactie. Had blijkbaar notificaties etc uit staan. 
Zie onderstaande error log. Kan je daar wat uit opmaken? Ik vind het ook raar aangezien de site geupdated is en uit niet meer bestaat dan Woocommerce, Elementor en jouw plugin. 

(In overleg met klant heb ik de sitena
[fatal-errors-2022-11-16-bbd2c3e237c3a71aa498126c1346a97a.log](https://github.com/patrickkivits/bunq-for-woocommerce/files/10098729/fatal-errors-2022-11-16-bbd2c3e237c3a71aa498126c1346a97a.log)
am even weggelaten).

**Comment by patrickkivits** [comment]
Hoi @tristanriethorst19,

Bedankt voor het logbestand. Het lijkt erop dat het fout gaat in een onderliggende dependency, namelijk Guzzle (deze wordt gebruikt om HTTP verzoeken te kunnen doen).

Weet je of de curl php extensie is geïnstalleerd en actief is? Deze is nodig voor het doet van de HTTP verzoeken in Guzzle. Zie ook https://github.com/patrickkivits/bunq-for-woocommerce/tree/v1.2.6#requirements

**Comment by tristanriethorst19** [comment]
@patrickkivits ga ik navragen. Dank voor het kijken. Hou je op de hoogte!

**Comment by tristanriethorst19** [comment]
Hi @patrickkivits, plesk panel van mijndomein zegt dat alle vereiste PHP extensies, dus ook curl, gewoon aanstaan. Zie screenshot voor meer details. De website draait op 8.1.13. Enig idee wat ik nog meer kan uitzoeken?

<img width="942" alt="Screenshot 2022-11-30 at 12 16 44" src="https://user-images.githubusercontent.com/118358529/204782938-e1a9b6a1-7a0f-4e7f-a4f6-37c274c5fe17.png">

**Comment by patrickkivits** [comment]
Hoi @tristanriethorst19, wat vreemd dat het niet wilt werken, ik heb de demo website op https://bunq-for-woocommerce.patrickkivits.com/ namelijk ook draaien op PHP 8.1: 
<img width="1351" alt="Scherm­afbeelding 2022-12-01 om 10 55 57" src="https://user-images.githubusercontent.com/727174/205023060-bc944ad3-0174-4fc8-9a52-cb95ed67b3c0.png">

Kun je vanuit Wordpress het nog eens checken in de **Site Health** tab, om zeker te zijn dat deze website daadwerkelijk deze PHP versie gebruikt? Je kunt in dit screenshot ook tevens de curl versie controleren dan.

**Comment by tristanriethorst19** [comment]
hi @patrickkivits ,

Zie onderstaande screenshot. Ziet ernaar uit dat alles gewoon overeenkomt, toch?
<img width="781" alt="Screenshot 2022-12-01 at 11 17 24" src="https://user-images.githubusercontent.com/118358529/205027808-6b4769b9-e0bc-4e57-84f8-5c730b3c26a3.png">

**Comment by tristanriethorst19** [comment]
Ha @patrickkivits,
Cannot redeclare bunq_add_gateway_class() (previously declared in /var/www/vhosts/druggy.nl/httpdocs/wp-content/plugins/bunq-for-woocommerce-master/bunq-for-woocommerce.php:32) in /var/www/vhosts/druggy.nl/httpdocs/wp-content/plugins/bunq-for-woocommerce/bunq-for-woocommerce.php on line 32

**Comment by patrickkivits** [comment]
Hoi @tristanriethorst19,

Je hebt denk ik de vorige plug-in nog actief. Je kan er maar 1 tegelijk actief hebben.

**Comment by tristanriethorst19** [comment]
Hi @patrickkivits ,

Excuses voor de late reactie. Zie bijgevoegd log bestand.
[log.txt](https://github.com/patrickkivits/bunq-for-woocommerce/files/10176031/log.txt)

**Comment by patrickkivits** [comment]
Hoi @tristanriethorst19 het lijkt erop dat hij nog steeds 2x dezelfde plugin ziet, kun je de andere (originele) plugin helemaal verwijderen en opnieuw proberen met alleen de aangepast plugin?
