### ISSUE TITLE
Betalingen via creditcard werken niet

### ISSUE THREAD

**Issue by prinsrob** [patrickkivits/bunq-for-woocommerce#13]
Bedankt voor deze mooie plugin. Als ik via mijn bunq.me een betaling doe via creditcard werkt dit wel. Via deze woocommerce plugin werkt iDEAL wel, maar creditcard niet. Ik krijg de volgende foutmelding:

De gekozen valuta "EUR" wordt niet ondersteund met je huidige lidmaatschap.

Ik heb het lidmaatschap Easy Money. Weet iemand waar het probleem kan liggen?

**Comment by prinsrob** [comment]
Ik ben niet de enige die die probleem heeft (gehad), zie: https://together.bunq.com/d/50050-bunq-as-a-payment-provider

[quote]
bunq does not allow usage of the card payments feature for commercial purposes. They are not a PSP after all, just providing banking services (albeit with an extensive API and more features than most other bank accounts, so I understand why you might want to use them as a PSP). While they do not explicitly disallow using any of the other payment methods like iDEAL, Sofort or Bancontact for business purposes
[/quote]

Is het het geval dat bunq credit card betalingen wellicht heeft uitgezet voor deze plugin?

[quote]
bunq.me functionality doesn't differ between the different business plans. The Terms of Service regarding card payments also apply to all plans in the same way.
[/quote]

Als dit klopt ligt het dus in ieder geval niet aan mijn lidmaatschap.

Het lijkt me dus dat dit een probleem is dat bij bunq ligt, en niet bij de plugin? Kunnen anderen ook niet gebruik maken van de credit card wanneer betaald wordt via deze plugin?

**Comment by patrickkivits** [comment]
Hoi @prinsrob,

De plugin zou alle beschikbare betaalmethoden van bunq.me aan moeten bieden, in de demo op https://bunq-for-woocommerce.patrickkivits.com kun je dit zelf ook zien.

Als dit voor jou niet het geval is, zal dit inderdaad iets zijn waar alleen bunq invloed op heeft, de plugin heeft hier zelf namelijk geen configuratie voor. Gebruik je misschien een zakelijke rekening? De demo is gebaseerd op een prive rekening.

Wel moet het bedrag passen binnen de eisen die bunq stelt aan de betaalmethoden (zie screenshots)

<img width="685" alt="Scherm­afbeelding 2023-04-14 om 08 50 47" src="https://user-images.githubusercontent.com/727174/231966201-166f73c2-ac31-4ba2-ad4f-d4e5dd57bcfa.png">
<img width="635" alt="Scherm­afbeelding 2023-04-14 om 08 48 58" src="https://user-images.githubusercontent.com/727174/231966214-b1aa63a0-c98e-483e-966e-ad557904fdff.png">

**Comment by prinsrob** [comment]
Ik gebruik zelf ook een prive rekening. Ik heb geprobeerd op de demopagina van je een euro over te maken met credit card, maar kreeg dezelfde foutmelding. Ik heb op mijn website deze melding gekregen met twee verschillende credit cards (en dacht daarom dus dat het niet specifiek aan een eventuele beperking op mijn credit card zit). Zou je (of iemand anders) kunnen laten weten of het wel of niet werkt met de credit card?
![creditcardfout](https://user-images.githubusercontent.com/98789338/232075646-97d38292-13e1-4c36-8ebc-f77805b0e139.PNG)

**Comment by patrickkivits** [comment]
Hoi @prinsrob, ik vrees dat het dan toch niet werkt met credit card inderdaad. Dit is iets wat aan de kant van bunq geregeld wordt, de plugin heeft hier geen invloed op.

De werking van deze plugin is natuurlijk ook een beetje "misbruik" maken van de bunq.me functionaliteit, het was door bunq nooit bedoeld geweest om bunq.me te gebruiken als payment gateway voor webshops.

Je zou contact kunnen opnemen met bunq support, wellicht hebben zei een verklaring waarom de credit card niet werkt.

**Comment by prinsrob** [comment]
Dank, dat vermoeden had ik inderdaad ook al. Wat mij betreft kan dit gesloten worden. Ik ga geen contact opnemen met bunq omdat ik mijn rekening dan wellicht niet helemaal correct gebruik en geen slapende honden wakker wil maken :-).
