### ISSUE TITLE
API key not valid or not setup yet

### ISSUE THREAD

**Issue by cannabisdoctor** [patrickkivits/bunq-for-woocommerce#16]
i get critical error after scanning auth code 

in store i see this error 
apiContext has not been loaded.

It has been working for years now 
thansk for that
i wish i used it sooner.

**Comment by cannabisdoctor** [comment]
On another server it works flawless so it must be server misconfiguration. Thank you Patrick

**Comment by patrickkivits** [comment]
Hi,

Thank you for your message, good to hear that you are able to make the plugin work on another server.

Is there any difference between these servers that could have caused this? Does the server meet all the [requirements](https://github.com/patrickkivits/bunq-for-woocommerce#requirements)?
