### ISSUE TITLE
Payment method not showing on checkout page

### ISSUE THREAD

**Issue by JesseFPV** [patrickkivits/bunq-for-woocommerce#17]
The bunq payment method is not showing up on the checkout page. However in admin the setup procedure worked fine, bunq connection made and bank account selected.

Woocommerce 8.3.0

Also shows ⚠ 1 Incompatible plugin detected (bunq for WooCommerce) in Advanced -> Features. Enabling compatibility mode did not solve the issue.

**Comment by patrickkivits** [comment]
Hi @JesseFPV, @108-Dev 

I've tested the plugin on the demo website https://bunq-for-woocommerce.patrickkivits.com with Wordpress version 6.4.1 and WooCommerce version 8.3.0 and the plugin version v1.2.7, without any issues. Also the warning about imcompatible plugin is not showing for me.

I did however create a new release ([v1.2.8](https://github.com/patrickkivits/bunq-for-woocommerce/releases/tag/v1.2.8)) that increases the "Tested up to" and "WC tested up to" to match the latest versions of Wordpress and WooCommerce, maybe you can try that one: https://github.com/patrickkivits/bunq-for-woocommerce/releases/tag/v1.2.8

Please let me know if this resolves the issue!

**Comment by JesseFPV** [comment]
I got it working by editing the Checkout page with Elementor and put the Elementor Checkout Box in the page. @108-Dev Could be an Elementor error. If you use elementor try this approach.

**Comment by 108-Dev** [comment]
> I got it working by editing the Checkout page with Elementor and put the Elementor Checkout Box in the page. @108-Dev Could be an Elementor error. If you use elementor try this approach.

Thanks for the tip. However I am not using Elementor...I updated to the new version but at no prevail. Payment option in checkout still doesn´t show up. (WP [6.4.1 version.])

**Comment by patrickkivits** [comment]
@JesseFPV Glad to hear it is working for you!

@108-Dev I'm pretty sure it is has something to do with your specific setup, could it be just a theme issue? Do other WooCommerce payment plugins work? Do they show up on the checkout page?

**Comment by 108-Dev** [comment]
> @JesseFPV Glad to hear it is working for you!
> 
> @108-Dev I'm pretty sure it has something to do with your specific setup, could it be just a theme issue? Do other WooCommerce payment plugins work? Do they show up on the checkout page?

Sorry for the late reply. I have been slacking...Other payment plugins do work. I was wondering if it was perhaps the theme but it´s all default without any edits (yet). I will try and switch to another.

**Comment by patrickkivits** [comment]
@JesseFPV I just figured out why the message about incompatible plugin is showing.

Please see my comment here: https://github.com/patrickkivits/bunq-for-woocommerce/issues/18#issuecomment-1916754414

**Comment by JesseFPV** [comment]
Excellent!
