### ISSUE TITLE
⚠ 1 Incompatible plugin detected (bunq for WooCommerce).

### ISSUE THREAD

**Issue by bobromeo** [patrickkivits/bunq-for-woocommerce#18]
Hi Patrick, thx for this plugin, i am using it on the donation site Eyes On Ukraine . eu
Woo: 8.5.1 b4W:1.2.8 (DL:25dec23)
This plugin is working okay for me, so this might a feature request :-)
At Settings> Advanced> Features> <-- ⚠ 1 Incompatible plugin detected (bunq for WooCommerce).
is shown.
It wanted to 'check' High-performance order storage and synchronized the orders, but I still can't choose it ..
¿Is there something i can do about this?

**Comment by patrickkivits** [comment]
Hi @bobromeo,

It seems that the plugin needed to explicitly declare compatibility with High-Performance Order Storage (HPOS).

I just released a new tag v1.2.9 with this change.

Can you please try this new pre-release: https://github.com/patrickkivits/bunq-for-woocommerce/releases/tag/v1.2.9

**Comment by bobromeo** [comment]
Hi Patrick, better late then never, I installed 1.2.9 and High-Performance Order Storage is now working, thx!
