### ISSUE TITLE
bunq does not support checkout with blocks

### ISSUE THREAD

**Issue by TrueFawkes** [patrickkivits/bunq-for-woocommerce#19]
When installing this psp, I could not find the checkout option on my checkout page.
When looking into editing the checkout page I found the following:

![image](https://github.com/patrickkivits/bunq-for-woocommerce/assets/24944520/a5dffb68-dec9-4916-8e7e-9e5d2868025f)
![image](https://github.com/patrickkivits/bunq-for-woocommerce/assets/24944520/e6202e16-1ac1-422c-a042-c6e858fc8dcf)

For now I'll check if I can make it work by reverting to the classic checkout.
https://woo.com/document/cart-checkout-blocks-status/

**Comment by patrickkivits** [comment]
Hi @TrueFawkes,

Thank you for opening this issue.

I looked into supporting cart and checkout blocks. It requires a bit more work than just simply “declaring compatibility”, but will try to add support for it.

I cannot promise any timeline, but I will try to find the time for it as soon as I can!

In the meantime only the classic cart and checkout are supported.

If there is anything you can do to help, I’m happy to accept pull requests.

**Comment by patrickkivits** [comment]
@TrueFawkes Please see the new v1.4.0 pre-release that includes support for WooCommerce Checkout Blocks: https://github.com/patrickkivits/bunq-for-woocommerce/releases/tag/v1.4.0
