### ISSUE TITLE
Er kan geen bankrekeningnummer gekozen worden. 

### ISSUE THREAD

**Issue by skyedesigns-nl** [patrickkivits/bunq-for-woocommerce#2]
Hallo,

Dank voor de plugin. Ik heb deze geïnstalleerd op mijn website, maar zie dat het ook niet lekker werkt.
Bij het invullen van de API sleutel die ik in de Bunq App heb gegenereerd, zie ik dat;

Er geen bankrekeningnummer gekozen kan worden. De melding "API Key not valid or not set up yet" is de enige optie in de dropdown

Het veld met de Live API Context blijft leeg en wordt niet ingevuld na het invullen van de API Sleutel

Hoe kan ik deze issues verhelpen?
Want ik kom er niet uit :(

Fijne Feestdagen

**Comment by patrickkivits** [comment]
Hoi @skyedesigns-nl,

In de plugin hoef je zelf geen API Sleutel in te vullen, maar vul je een **Client ID** en **Client Secret** in. Na de [configuratie](https://github.com/patrickkivits/bunq-for-woocommerce#configuration) wordt de API sleutel vanzelf ingevuld. Het veld API Sleutel in de plugin is als het goed is ook read-only.

Heb je alle stappen van de [configuratie](https://github.com/patrickkivits/bunq-for-woocommerce#configuration) correct doorlopen?

**Comment by skyedesigns-nl** [comment]
Ja alles is echt goed gedaan. Tot na qr code.. pagina kom ik terug zeg maar. Maar er staat geen rekening die ik kan selecteren in de drop down

Je kan mij mailen op info @ skyedesigns .nl
Als jij laat zien hoe het werkt en het werkt doneer ik graag hier aan.

Misschien teamviewer sessie?

Hoor graag van je via de mail

**Comment by skyedesigns-nl** [comment]
apiContext has not been loaded. Krijg ik bij checkout ivm geen rekening nummer te kiezen in drop down 'API not valid or not setup yet'

**Comment by skyedesigns-nl** [comment]
10. Select your Bank account and Enable the plugin and Save changes.

Dit laatste puntje lukt niet

**Comment by patrickkivits** [comment]
Ik heb je zojuist een mailtje gestuurd.

**Comment by skyedesigns-nl** [comment]
Bedankt voor de hulp

**Comment by tj1199** [comment]
Hi Patrick,
Ik heb exact hetzelfde probleem als skydesigns-nl.
Ik hoor graag van je hoe ik dit op kan lossen.

Vriendelijke groet
