### ISSUE TITLE
Error: Verifying response failed. when checking out

### ISSUE THREAD

**Issue by filoor** [patrickkivits/bunq-for-woocommerce#22]
Hi Patrick,

I have installed the latest (pre)release and linked my bank account. I've also selected the correct account in settings. However, when attempting to make a payment, I encounter an error: "Verifying response failed." I can see on Bunq that the payment link is being created, but the issue arises when trying to complete the transaction.

**Comment by patrickkivits** [comment]
Hi @filoor,

Thanks, it seems that the v1.2.12 pre-release indeed still did not solve the bug for https://github.com/patrickkivits/bunq-for-woocommerce/issues/20.

I've created a new pre-release v1.2.13, this should now resolve the issue: https://github.com/patrickkivits/bunq-for-woocommerce/releases/tag/v1.2.13

Please let me know if you still have any issue after updating to v1.2.13

**Comment by filoor** [comment]
Hi Patrick,


stil the same error [07-Mar-2024 20:14:24 UTC] Verifying response failed.
[07-Mar-2024 20:14:25 UTC] HTTP Response Code: 429
The response id to help bunq debug: 71cd9336-f82a-4de9-b787-7d6f386563be

**Comment by patrickkivits** [comment]
Hi @filoor,

Can you please redo the “ OAuth Authorization Request” flow? That should solve the issue, and remain fixed once that is done.

**Comment by filoor** [comment]
Yes, that helped Thank you, but after making the payment, I remain on the payment QR code screen and am not redirected back to my page.

**Comment by patrickkivits** [comment]
Hi @filoor 

This is a known issue which unfortunately i cannot solve, please check this previous issue for more information about this: https://github.com/patrickkivits/bunq-for-woocommerce/issues/21
