### ISSUE TITLE
Bunq Webpage stays on loading payment.

### ISSUE THREAD

**Issue by JesseFPV** [patrickkivits/bunq-for-woocommerce#31]
When selecting iDeal or Credit Card in the Bunq payment page the page keeps loading. While using a Bunq payment link generated from the Bunq app it does load the payment.

<img width="530" alt="Screenshot 2024-10-13 at 13 39 49" src="https://github.com/user-attachments/assets/de6617c3-6a06-4454-a67b-6ee790bc965a">

**Comment by JesseFPV** [comment]
After redoing the OAuth Authorization Request the Live API Key and Live API Context input fields remain empty. Also tried the latest 1.4.2 (master branch) instead of the latest version in releases. Same result

**Comment by patrickkivits** [comment]
Hi @JesseFPV ,

This is a known issue, which unfortunately I cannot fix.

Ever since bunq released ideal 2.0, the payment requests created by their API have this problem.

My hope is that they will resolve this issue, that’s all we can do for now.

**Comment by JesseFPV** [comment]
Thank you Patrick, I'm sorry I see this issue was already posted. I will close it to remain a clean overview. Best regards!
