### ISSUE TITLE
Apicontext is empty

### ISSUE THREAD

**Issue by doekoema** [patrickkivits/bunq-for-woocommerce#5]
Hi,

I am trying to install it on WP5,7 and Wo 5.1
and when I do the authorization the apicontext keeps empty.

Please advise ?

**Comment by patrickkivits** [comment]
Hi Doekema,

Did you check all the requirements on your webshop environment? 

https://github.com/patrickkivits/bunq-for-woocommerce#requirements

Looks like some issue with OpenSSL that I have seen before...

**Comment by patrickkivits** [comment]
Closed due to inactivity, please let me know if you still need any help.
