### ISSUE TITLE
Fatal error on clean WP

### ISSUE THREAD

**Issue by RVanDamage** [patrickkivits/bunq-for-woocommerce#8]
Hi!

We installed this module on a clean WP last week. Everything works, but every night we receive an email with a fatal error (sent by the WP built-in tool) and it says:

Error details
===========
An error of type E_ERROR was caused on line number 34 of the file /var/www/vhosts/dev-domain.com/wp-content/plugins/bunq-for-woocommerce-1.2.2/includes/bunq.php.
Error: Uncaught Error: Call to a member function ensureApiLimitsAreRespected() on null in /var/www/vhosts/dev-domain.com/wp-content/plugins/bunq-for-woocommerce-1.2.2/includes/bunq.php:34

Stack trace:
#0 /var/www/vhosts/dev-domain.com/wp-content/plugins/bunq-for-woocommerce-1.2.2/bunq-for-woocommerce.php(403): bunq_load_api_context_from_json()
#1 /var/www/vhosts/dev-domain.com/wp-content/plugins/bunq-for-woocommerce-1.2.2/bunq-for-woocommerce.php(213): WC_Bunq_Gateway->load_api_context()
#2 /var/www/vhosts/dev-domain.com/wp-content/plugins/bunq-for-woocommerce-1.2.2/bunq-for-woocommerce.php(63): WC_Bunq_Gateway->init_form_fields()
#3 /var/www/vhosts/dev-domain.com/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(97): WC_Bunq_Gateway->__construct()
#4 /var/www/vhosts/dev-domain.com/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(70): WC_Payment_Gateways->init()
#5 /var/www/vhosts/dev-domain.com

**WordPress version: 5.9.3
Bunq for WooCommerce (versie 1.2.2)
PHP version 7.4.28**

**Comment by patrickkivits** [comment]
Hi @RVanDamage,

I am not able to reproduce this error, do you have any idea why this error occurs only at night? Is it always at the same time? How often does it happen (per night)?

Thanks!

**Comment by RVanDamage** [comment]
Hi @patrickkivits,

It's always at the same time because I see in the logs that around 2.30 AM the wp-cron.php is executed.
It's just the default WP check. So I'm guessing the error is there constantly.

If you want I can forward the email to you? Like I said it's the WP core who is sending this email, saying there's an technical issue with a plugin.

It happens once per night.

**Comment by RVanDamage** [comment]
Hi @patrickkivits,

We've got that email again, with same error details.


_Howdy!_

_Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email._

_In this case, WordPress caught an error with one of your plugins, bunq for WooCommerce._

_First, visit your website and check for any visible issues. Next, visit the page where the error was caught and check for any visible issues._

_Please contact your host for assistance with investigating this issue further._

_If your site appears broken and you can't access your dashboard normally, WordPress now has a special "recovery mode". This lets you safely login to your dashboard and investigate further._

**Comment by patrickkivits** [comment]
Hi @RVanDamage,

I have just released a new release of the plugin (v1.2.4), please try to install this version and see if the issue resolves: https://github.com/patrickkivits/bunq-for-woocommerce/releases/tag/v1.2.4

Please let me know if the issues is resolved or not.

**Comment by RVanDamage** [comment]
Hi @patrickkivits,

Awesome, I just installed it.
What I noticed is this I have the plugin showing twice now, and I've checked filemanager and it's because the version number is in the folder name. This happens automatically when uploading the ZIP file from Github.

Maybe I should remove the version number, and reinstall?

Check screenshot:
![plugin-folder](https://user-images.githubusercontent.com/68848292/163139430-95c2b1a2-cb24-411d-bf19-26b6eecb9aad.png)

**Comment by patrickkivits** [comment]
Hi @RVanDamage,

All you need to do is delete the old version. You can also rename to just bunq-for-woocommerce if you like...

**Comment by RVanDamage** [comment]
Hi @patrickkivits,

Ok I thought maybe the version number was causing an issue. 
Anyway, we just installed latest version. So now let's wait until tonight :)

**Comment by patrickkivits** [comment]
Hi @RVanDamage,

Is the issue resolved?

**Comment by RVanDamage** [comment]
Hi @patrickkivits, I think it is :)
Haven't received the error email anymore. So far so good. Thanks!
